server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /test
    # rabbitmq 消费者监听配置
    listener:
      simple:
        concurrency: 5 # 消费端的监听个数(即@RabbitListener开启几个线程去处理数据。)
        max-concurrency: 10 #最大并发
        acknowledge-mode: manual # 签收模式
        prefetch: 1 # 消费端限流 ，每个线程最多取一个数据
